// flow-typed signature: 82ab448f81b4aa3a18558d192c97f787
// flow-typed version: <<STUB>>/@crestron/ch5-crcomlib_v1.0.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@crestron/ch5-crcomlib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@crestron/ch5-crcomlib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@crestron/ch5-crcomlib/build_bundles/amd/cr-com-lib' {
  declare module.exports: any;
}

declare module '@crestron/ch5-crcomlib/build_bundles/cjs/cr-com-lib' {
  declare module.exports: any;
}

declare module '@crestron/ch5-crcomlib/build_bundles/umd/cr-com-lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@crestron/ch5-crcomlib/build_bundles/amd/cr-com-lib.js' {
  declare module.exports: $Exports<'@crestron/ch5-crcomlib/build_bundles/amd/cr-com-lib'>;
}
declare module '@crestron/ch5-crcomlib/build_bundles/cjs/cr-com-lib.js' {
  declare module.exports: $Exports<'@crestron/ch5-crcomlib/build_bundles/cjs/cr-com-lib'>;
}
declare module '@crestron/ch5-crcomlib/build_bundles/umd/cr-com-lib.js' {
  declare module.exports: $Exports<'@crestron/ch5-crcomlib/build_bundles/umd/cr-com-lib'>;
}
